services:
  postgres:
    image: postgres:17
    container_name: vault-postgres
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '23423:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
